### ISSUE TITLE
prune2df warning messages

### ISSUE THREAD

**Issue by TobiTekath** [aertslab/pySCENIC#106]
Hi,
thanks for developing this very useful toolkit.

I am wondering, if it is normal/expected to get so many warnings messages while performing `prune2df`.
I get warning messages like 

`pyscenic.transform - WARNING - Less than 80% of the genes in some_gene could be mapped to hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr.feather. Skipping this module.`
 
or 

`pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for some_regulon could be mapped to hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.feather. Skipping this module.`

I get these warnings with the two hg38-Database files as well as with the six hg19-Database files - so the hg-version of the db does not seem to be the cause. My data is annotated with gencode, so it should be hg38.

The results of the `prun2df()` do look quite good, I am just not sure about the ~29000 warning messages I get in the process.

_______
My `prune2df` call looks like this
`df = prune2df(rnkdbs=dbs, modules=modules, motif_annotations_fname=MOTIF_ANNOTATIONS_FNAME, client_or_address="custom_multiprocessing", num_workers=30)
`

with dbs: `[FeatherRankingDatabase(name="hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr.feather"),
 FeatherRankingDatabase(name="hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.feather")]`

and

`[FeatherRankingDatabase(name="hg19-500bp-upstream-7species.mc9nr.feather"),
 FeatherRankingDatabase(name="hg19-500bp-upstream-10species.mc9nr.feather"),
 FeatherRankingDatabase(name="hg19-tss-centered-5kb-7species.mc9nr.feather"),
 FeatherRankingDatabase(name="hg19-tss-centered-5kb-10species.mc9nr.feather"),
 FeatherRankingDatabase(name="hg19-tss-centered-10kb-7species.mc9nr.feather"),
 FeatherRankingDatabase(name="hg19-tss-centered-10kb-10species.mc9nr.feather")]`

respectively. I am using `motifs-v9-nr.hgnc-m0.001-o0.0.tbl` as motif annotation and `hs_hgnc_curated_tfs.txt` as tfs.

I am using pyscenic version 0.9.19.

Thanks in advance.

**Comment by alyamahmoud** [comment]
I am getting the same error message while using the python version of pySCENIC (not the command line version). Is there something that pops up particularly with hg38 ?

**Comment by TobiTekath** [comment]
Just as an quick update: I see the same warning messages when using the CLI-Version as well as in Jupyter.

@bramvds It would be great, if you could clarify if it is expected to have so many warnings. At least I see other people (#138) experiencing the same Warning messages.

**Comment by cflerin** [comment]
It's normal to have 10s or 100s of these warnings when running the pruning step (and it's a warning, not an error). The cause is just what it states: for a given module that is being pruned, there are not enough genes present that overlap with the database. The module is then excluded from further analysis.

**Comment by prullens** [comment]
Doesn't 80% seem a bit rigid? I'd be happy if ~50% of the module targets have motif enrichment. Or am I misinterpreting something? Could one for example manually lower this percentage for modules to be included in further analysis? In my dataset an unfortunate number of interesting TFs are excluded consequent to this threshold. 

Best,

**Comment by RinconFer** [comment]
> I would like to chime in here and bump this issue. How can I lower the 80% cutoff? I end up with only 26 transcription factor activity matrix in the end of pyscenic due to this pruning step.

I would also like to know this, in my dataset is pruning hundreds of regions, some of them really interesting to me.

Thank you

**Comment by RinconFer** [comment]
> @RinconFer I just created a pull request #387 for pySCENIC which will allow you to change the cutoff. I can obviously not 100% guarantee that it works as expected but in my test runs it did.
> 
> You can test it in your setting using the following conda environment:
> 
> ```shell
> conda create -n pyscenic-test python=3.7 pip git
> conda activate pyscenic-test
> pip install git+https://github.com/klprint/pySCENIC@relax_module2df
> ```

Thank you very much!!

I'll test it as soon as possible and let you know how it goes.

**Comment by klprint** [comment]
FYI the parameter for chaning the cutoff is the following. Forgot to add it in my previous message.

```bash
pyscenic ctx \
    .... \
    --frac_mapping_module 0.8 \
    ....
```

**Comment by Beki-seq** [comment]
> FYI the parameter for chaning the cutoff is the following. Forgot to add it in my previous message.
> 
> ```shell
> pyscenic ctx \
>     .... \
>     --frac_mapping_module 0.8 \
>     ....
> ```

Hello, 
I meet exactly same issue with you guys. I also tried to use the command you give to solve the problem, however, my pyscenic said the cannot recognize frac_mapping_module 0.8. I am wondering is there any specific order for the --frac_mapping_module comman? 

And my code is:
pyscenic ctx \
adj.sample.tsv $feather \
--annotations_fname $tbl \
--frac_mapping_module 0.8 \
--expression_mtx_fname $input_loom  \
--mode "dask_multiprocessing" \
--output reg.csv \
--num_workers 20  \
--mask_dropouts

**Comment by li-xuyang28** [comment]
> @RinconFer I just created a pull request #387 for pySCENIC which will allow you to change the cutoff. I can obviously not 100% guarantee that it works as expected but in my test runs it did.
> 
> You can test it in your setting using the following conda environment:
> 
> ```shell
> conda create -n pyscenic-test python=3.7 pip git
> conda activate pyscenic-test
> pip install git+https://github.com/klprint/pySCENIC@relax_module2df
> ```

Thanks for implementing the module cutoff, which is definitely much needed. However, I ran into the following error when setting the cutoff to 0.5:

IndexError: boolean index did not match indexed array along dimension 0; dimension is 55 but corresponding boolean dimension is 107

Could you please suggest/advise on how to resolve it? Thanks again.

**Comment by klgoss** [comment]
Hello, I wanted to bump this as I'm experiencing the same issue as @li-xuyang28 . I've installed the pyscenic-test environment as @klprint described above, but am met with the following error: `pyscenic: error: unrecognized arguments: --frac_mapping_module 0.5` 

Any insight is greatly appreciated!

**Comment by LacquerHed** [comment]
Having the same issue as @klgoss above, test environment does not contain the argument `--frac_mapping_module`

**Comment by DiracZhu1998** [comment]
> > @RinconFer I just created a pull request #387 for pySCENIC which will allow you to change the cutoff. I can obviously not 100% guarantee that it works as expected but in my test runs it did.
> > You can test it in your setting using the following conda environment:
> > ```shell
> > conda create -n pyscenic-test python=3.7 pip git
> > conda activate pyscenic-test
> > pip install git+https://github.com/klprint/pySCENIC@relax_module2df
> > ```
> 
> Thanks for implementing the module cutoff, which is definitely much needed. However, I ran into the following error when setting the cutoff to 0.5:
> 
> IndexError: boolean index did not match indexed array along dimension 0; dimension is 55 but corresponding boolean dimension is 107
> 
> Could you please suggest/advise on how to resolve it? Thanks again.

Hey Xuyang, I was wondering have you solve this problems? Many thanks!

**Comment by DiracZhu1998** [comment]
> > @RinconFer I just created a pull request #387 for pySCENIC which will allow you to change the cutoff. I can obviously not 100% guarantee that it works as expected but in my test runs it did.
> > You can test it in your setting using the following conda environment:
> > ```shell
> > conda create -n pyscenic-test python=3.7 pip git
> > conda activate pyscenic-test
> > pip install git+https://github.com/klprint/pySCENIC@relax_module2df
> > ```
> 
> Thanks for implementing the module cutoff, which is definitely much needed. However, I ran into the following error when setting the cutoff to 0.5:
> 
> IndexError: boolean index did not match indexed array along dimension 0; dimension is 55 but corresponding boolean dimension is 107
> 
> Could you please suggest/advise on how to resolve it? Thanks again.
<img width="977" alt="Screenshot 2024-01-31 at 20 18 52" src="https://github.com/aertslab/pySCENIC/assets/47734593/bdeaf55d-5bd6-4a06-9183-3351c43f1826">

I just solved it, you could check source code and pay attention to "annotated_features" variable which most likely will have duplicated motifIDs. I changed all gene to Ensembl ID based on its Gene name and Gene Synonym retrieved from Ensembl since some genes SCENIC used was synonym rather than gene name. but some genes like Atf5 has a symbol name called Atf7, causing two ENSMUSG00000038539 ~ cisbp__M0302 line in annotated_features variable, which further caused the purne steps "dimension" bug.

**Comment by TamiaChin** [comment]
> > > [@RinconFer](https://github.com/RinconFer) I just created a pull request [#387](https://github.com/aertslab/pySCENIC/pull/387) for pySCENIC which will allow you to change the cutoff. I can obviously not 100% guarantee that it works as expected but in my test runs it did.
> > > You can test it in your setting using the following conda environment:
> > > conda create -n pyscenic-test python=3.7 pip git
> > > conda activate pyscenic-test
> > > pip install git+https://github.com/klprint/pySCENIC@relax_module2df
> > 
> > 
> > Thanks for implementing the module cutoff, which is definitely much needed. However, I ran into the following error when setting the cutoff to 0.5:
> > IndexError: boolean index did not match indexed array along dimension 0; dimension is 55 but corresponding boolean dimension is 107
> > Could you please suggest/advise on how to resolve it? Thanks again.
> 
> <img alt="Screenshot 2024-01-31 at 20 18 52" width="977" src="https://private-user-images.githubusercontent.com/47734593/301296494-bdeaf55d-5bd6-4a06-9183-3351c43f1826.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAzOTg0MzksIm5iZiI6MTc0MDM5ODEzOSwicGF0aCI6Ii80NzczNDU5My8zMDEyOTY0OTQtYmRlYWY1NWQtNWJkNi00YTA2LTkxODMtMzM1MWM0M2YxODI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjI0VDExNTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1OTBhYWZlYmJjNzBiYzM3Yzk0MjRkZmFmY2UxZDI1ZWFhNDExZGNiZjk1ODgxMzdkODA3ZjJlNDg0MTQ0YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6Ib8cIkeBMoLCD5Tzt4cqV5xd1T-QrUAkqC6WcR6f1Y">
> I just solved it, you could check source code and pay attention to "annotated_features" variable which most likely will have duplicated motifIDs. I changed all gene to Ensembl ID based on its Gene name and Gene Synonym retrieved from Ensembl since some genes SCENIC used was synonym rather than gene name. but some genes like Atf5 has a symbol name called Atf7, causing two ENSMUSG00000038539 ~ cisbp__M0302 line in annotated_features variable, which further caused the purne steps "dimension" bug.

could you please kindly share your method. I now understand that duplicated annotated features caused this error but still don't know how to effectively remove them. Many thanks!!

**Comment by DiracZhu1998** [comment]
The code for solution: 
library(arrow)
library(Seurat)
library(dplyr)

gene_info <- read.delim("0.human_gene_info_from_Ensembl.mod", header =T, sep = "\t")
feather1 <- read_feather("cisTargets/hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr.feather")
feather2 <- read_feather("cisTargets/hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.feather")

gene_info[gene_info$Gene.name == NULL, "Gene.name"] <- gene_info[gene_info$Gene.name == NULL, "Gene.stable.ID"]
gene_info[gene_info$Gene.name == NULL, "Gene.Synonym"] <- gene_info[gene_info$Gene.name == NULL, "Gene.stable.ID"]

Ensembl <- list()
for (i in 1:nrow(gene_info)){
    tryCatch({Ensembl[[gene_info[i, 2]]] <- unique(c( Ensembl[[gene_info[i, 2]]], gene_info[i, 1]))},
        error = function(e){Ensembl[[gene_info[i, 2]]] <- gene_info[i, 1] })
    tryCatch({Ensembl[[gene_info[i, 3]]] <- unique(c( Ensembl[[gene_info[i, 3]]], gene_info[i, 1]))},
        error = function(e){Ensembl[[gene_info[i, 3]]] <- gene_info[i, 1] })
}

# some genes are not exist in Ensembl biomart, keep it as original name, e.g., 0610010B08Rik
# some lncRNA has relationships with two gene IDs, like 1700030C10Rik corresponding to ENSMUSG00000099759 and ENSMUSG00000091071
# I also wouldn't change these genes ID, it doesn't matter actually since for our scRNA analysis we only focus on coding genes.
colnames(feather1)[2:ncol(feather1)] <- setNames(vapply(colnames(feather1)[2:ncol(feather1)],
                                                        FUN = function(g){ if (length(Ensembl[[g]]) == 1){
                                                            Ensembl[[g]] } else {
                                                                g }}, FUN.VALUE=character(1)), NULL)
colnames(feather2)[2:ncol(feather2)] <- setNames(vapply(colnames(feather2)[2:ncol(feather2)],
                                                        FUN = function(g){ if (length(Ensembl[[g]]) == 1){
                                                            Ensembl[[g]] } else {
                                                                g }}, FUN.VALUE=character(1)), NULL)
# A730008H23Rik Hjurp is same gene in latest version Ensembl, but feather file contain both column, there are several other few cases like this.
# only keep first occurence, this is an essential step
duplicated1 <- table(colnames(feather1))
duplicated1 <- names(duplicated1)[duplicated1 >= 2]
for (i in duplicated1){
    tmp <- which(colnames(feather1) == i)
    feather1[, tmp[1:length(tmp)]] <- NULL # remove all occurence!
}
duplicated2 <- table(colnames(feather2))
duplicated2 <- names(duplicated2)[duplicated2 >= 2]
for (i in duplicated2){
    tmp <- which(colnames(feather2) == i)
    feather2[, tmp[1:length(tmp)]] <- NULL # remove all occurence!
}

#write_feather(feather1, sink = "cisTargets/hg38-500bp.feather", version = 1)
#write_feather(feather2, sink = "cisTargets/hg38-tss-centered-10kb.feather", version = 1)

atlas <- readRDS("/mnt/data01/yuanzhen/01.Vertebrate_cell_evo/01.data/02.atlas/human/human_atlas_test_subset_100k.rds")
cell2cluster <- read.table("/mnt/data01/yuanzhen/01.Vertebrate_cell_evo/01.data/02.atlas/human_mouse_lizard/s4.harmony_final/cell_clusters.integrated.txt", header = T)
atlas@meta.data$species <- "Human"
atlas@meta.data$integrated_cluster <- vapply(colnames(atlas), FUN = function(x){
                                                 tmp <- cell2cluster[cell2cluster$cell_id == x, "clusters"]
                                                 if (length(tmp) == 0){
                                                     tmp <- 0
                                                 }
                                                 return(tmp)
        }, FUN.VALUE = double(1))

exprMat <- GetAssayData(atlas, layer = "counts")
rownames(exprMat) <- setNames(vapply(rownames(exprMat), FUN = function(g) {
                                  if (length(Ensembl[[g]]) == 1){
                                      Ensembl[[g]] } else { g }}, FUN.VALUE=character(1)), NULL)

LogexprMat <- GetAssayData(atlas, layer = "data")
rownames(LogexprMat) <- setNames(vapply(rownames(LogexprMat), FUN = function(g) {
                                    if (length(Ensembl[[g]]) == 1){
                                        Ensembl[[g]] } else { g }}, FUN.VALUE=character(1)), NULL)

cellInfo <- atlas@meta.data
cellInfo$CellType <- cellInfo$supercluster

saveRDS(exprMat, file = "exprMat.rds")
saveRDS(LogexprMat, file = "LogexprMat.rds")
saveRDS(cellInfo, file = "cellInfo.rds")
