### ISSUE TITLE
question about "grnboost"

### ISSUE THREAD

**Issue by xiexiaowei** [aertslab/pySCENIC#18]
Dear authors,
Recently, I used your powerful pySCENIC software and I met a question.

I have installed pyscenic successfully in our linux machine. But when I ran "pyscenic grnboost", I met error log as follows:

/public1/users/xxw/.local/lib/python3.5/site-packages/dask/dataframe/utils.py:480: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version of pandas will change to not sort by default.
To accept the future behavior, pass 'sort=False'.
To retain the current behavior and silence the warning, pass 'sort=True'. dtypes = pd.concat([x.dtypes, meta.dtypes], axis=1)
/public1/users/xxw/.local/lib/python3.5/site-packages/arboreto/algo.py:214: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead. expression_matrix = expression_data.as_matrix()
2018-08-28 23:17:31,233 - pyscenic.cli.pyscenic - INFO - Writing results to file.

preparing dask client
parsing input
creating dask graph
32 partitions
computing dask graph
not shutting down client, client was created externally
finished

Future exception was never retrieved
future: <Future finished exception=StreamClosedError('Stream is closed',)>
Traceback (most recent call last):
  File "/public1/users/xxw/.local/lib/python3.5/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/public1/users/xxw/.local/lib/python3.5/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/public1/users/xxw/.local/lib/python3.5/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/public1/users/xxw/.local/lib/python3.5/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
tornado.iostream.StreamClosedError: Stream is closed

Question: 
Because I could run "ctx" and "aucell" based on the output from "grnboost", I thougt that this error didn't matter.
However, when I repeated "grnboost", "ctx" and "aucell" again with the identical data/parameter, the output is different.
What's wrong with it and how can I solve this problem?

I need your help urgently and show my great appreciation to you!
xiaowei，

**Comment by jamesrhowe** [comment]
Just wanted to chime in here, I got the same thing too when running it from python on macOS. I haven't tried to reproduce it though, because it worked for me in downstream analysis as well.

Thanks a bunch!

**Comment by bramvds** [comment]
Dear James, Dear Xiaowei,

Regarding reproducing results, the difference in the final output is caused by the GRNBoost step which is actually a shortcut to the python package arboreto (https://github.com/tmoerman/arboreto). As explained in the FAQ for this package, GRNBoost2 is based on stochastic machine learning techniques, which use a random number generator internally to perform random sub-sampling of observations and features when building decision trees. More info can be found here: https://arboreto.readthedocs.io/en/latest/troubleshooting.html#q-different-runs-produce-different-network-outputs-why

The error message should not be problematic and is not related to 'irreproducibility' of the exact same output over different runs.

Hope this helps.

Kindest regards,
Bram
