### ISSUE TITLE
gene_names in arboreto is not defined

### ISSUE THREAD

**Issue by chansigit** [aertslab/pySCENIC#183]
A code issue that is very easy to solve.

In https://github.com/aertslab/pySCENIC/blob/master/scripts/arboreto_with_multiprocessing.py, 

the gene_names appears firstly in https://github.com/aertslab/pySCENIC/blob/c73e44b7628209576215259df9b6ec08c515a3d8/scripts/arboreto_with_multiprocessing.py#L104,

this variable is not locally defined in the run_infer_partial_network() function.

This may cause problems. On my windows computer, python interpreter failed and complained:
```
Traceback (most recent call last):
  File "C:\Users\86139\.conda\envs\r40py36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\86139\home\arboreto_with_multiprocessing.py", line 74, in run_infer_partial_network
    target_gene_name = gene_names[target_gene_index]
NameError: name 'gene_names' is not defined
```

However, this script worked well on my Linux system, it's amazing.

Can you please refine this code and define the gene_names variable locally within the function run_infer_partial_network?

**Comment by CurlsForScience** [comment]
I am also having an issue with this. I have the following error.

 File "arboreto_with_multiprocessing.py", line 75, in run_infer_partial_network
    target_gene_name = gene_names[target_gene_index]
NameError: name 'gene_names' is not defined

I am running on a MacOS 10.15.5 in a conda env.
I am also unable to run pyscenic grn due to the previously discussed dask issues.

If you require more information for this problem please let me know. I'd very much like to use pySCENIC, but I'm not sure how to move beyond this step given the issues.

Thank you.

**Comment by cflerin** [comment]
Hi @chansigit , @CurlsForScience , I'm guessing the problem is happening when you run this in Python 3.8? I'm able to replicate this error in `3.8.3`, but it still works for me in `3.7.7` and `3.6.10`. There were some changes to the way multiprocessing is implemented in 3.8 and I guess that's causing the problem here. For now, I'd recommend using Python 3.7 until I figure out how to handle this for 3.8.

**Comment by chansigit** [comment]
unfortunately, my python 3.6.10 on win10 doesn't work either. 
Please fix it. thank you so much.

**Comment by rb56** [comment]
Hi,

I'm having the same error- 
target_gene_name = gene_names[target_gene_index]
NameError: name 'gene_names' is not defined

Any way to fix this?
