### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by luying616** [aertslab/pySCENIC#191]
**Describe the bug**

**Steps to reproduce the behavior**
1. Command run when the error occurred:

```python
conda activate scenic_protocol
```

2. Error encountered:

```pytb
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

```

**Expected behavior**

**Please complete the following information:**
- pySCENIC version: [e.g. 0.10.0, use `pyscenic -h` at the command line]
- Installation method: [e.g. Conda, Pip, Docker, Singularity]
- Run environment: [e.g. Jupyter notebook, CLI, Nextflow, HPC script]
- OS: [e.g. Ubuntu]
- Package versions: [obtain using `pip freeze`, `conda list`, or skip this if using Docker/Singularity]:

```
- pySCENIC version: 0.10.3 
- Installation method: Pip
- Run environment: CLI
- OS: Centos
- conda versions: 4.8.3

```

**Comment by luying616** [comment]
I tried "conda init shell" command, but it did not work for me.

**Comment by cflerin** [comment]
It looks like your Conda install wasn't completed. I'll point you to the [Conda install docs](https://docs.anaconda.com/anaconda/user-guide/faq/#installing-anaconda), particularly the section "Should I add Anaconda to the macOS or Linux PATH?". This should hopefully fix your conda and you should be able to install pySCENIC within that conda environment.

I'm going to close this since it's not directly related to pySCENIC, but if you have any other install issues feel free to ask further here.
