### ISSUE TITLE
[bug] The background using python scripts running pyscenic triggerred error instead of jupyter-notebook in same miniconda environment

### ISSUE THREAD

**Issue by honghh2018** [aertslab/pySCENIC#205]
Hi @all，
     I met a weird problem that i paste the jupyter-notebook's entire codes that can run successfully at jupyter  into backgroup python scripts, then runing python pyscenic_analysis.py showing error the module not found.
     Even though the  pyscenic_analysis.py scripts running at the same miniconda environment just like the jupyter-notebook, it 
 still display the module no found. 
     So, this issues make me confused a lot. why the script file  pyscenic_analysis.py will contribute to this error ?
      the error showing below,
      
![image](https://user-images.githubusercontent.com/41668708/91830107-e45ec900-ec74-11ea-89df-b0373c7c5e1a.png)
i really assure that the module pyscenic had exist.
   But when i type into the python environment using import pyscenic showing same error module no found
    Any advice would be appreciated.
    Regards,
    hanhuihong

**Comment by cflerin** [comment]
Hi @honghh2018 ,

I would guess that there's something wrong with your python environment or pySCENIC install or that your conda environment isn't active. But I can only guess since you haven't included any of the requested information in the bug report template. If you want any further help with this, you can open a new bug report issue and included this info.

If you're trying to export the pySCENIC results into a loom file for use in SCope I'd suggest that you look [here](https://pyscenic.readthedocs.io/en/latest/faq.html#how-can-i-create-a-scope-compatible-loom-file) instead of using `export2loom`.

**Comment by honghh2018** [comment]
@cflerin 
 Thanks for those advices.
  This issue probably was a bug for me, because of the jupyter-notebook can finished the all pyscenic analysis without wrong instead of the python script i post before. and i never saw this issue before.  I would check the pyscenic miniconda environment, if necessity, i would open new issues with the bug description.
    About your SCope advice, i really like to try but the url of wget can not be download,
     wget https://raw.githubusercontent.com/vib-singlecell-nf/scenic/master/bin/add_visualization.py
     wget https://raw.githubusercontent.com/vib-singlecell-nf/scenic/master/bin/export_to_loom.py
     the scripts can not be download throug wget function.
     the error showing below,
     --2020-09-02 09:53:31--   https://raw.githubusercontent.com/vib-singlecell-nf/scenic/master/bin/add_ visualization.py
Resolving host raw.githubusercontent.com  ( raw.githubusercontent.com )... 0.0.0.0, ::
Connecting raw.githubusercontent.com  ( raw.githubusercontent.com ）|0.0.0.0 | 443... Failed: refused connection.
Connecting raw.githubusercontent.com  ( raw.githubusercontent.com ）|: |: 443... Failed: refused connection.
