### ISSUE TITLE
Running pySCENIC for finding condition-specific as well as cell-type specific regulons.

### ISSUE THREAD

**Issue by Manikgarg** [aertslab/pySCENIC#209]
Hi! I want to analyze how the top 5 regulons for different cell-types change with condition. Do you recommend subsetting the dataset for each condition separately and then following the pySCENIC pipeline to obtain the cell-type specific regulons or do you recommend running pySCENIC on all the data together and then calculating RSS for each cell-type separately for each condition (by subsetting the cells (and auc_mtx?) in the function `regulon_specificity_scores()` to each condition)? I understand that it might be faster to run pySCENIC on condition-specific subsets as I have ~87000 cells in total but I also want to be sure that subsetting the data won't introduce any possible error in calculations (for example, while calculating gene co-expression matrices). Please let me know. Thanks!

**Comment by cflerin** [comment]
Hi @Manikgarg ,

Take a look at #189  and #185. Generally I would try both (if you have the computational resources for the combined set).

For the RSS, you will get the "most specific" regulons by comparing Louvain/Leiden clusters calculated from the AUC matrix since this directly represents the underlying regulons. But the AUCell clusters won't necessarily divide your cells the same way as celltype or condition. So realistically, I think you'll have to run RSS using these classifications as well. I can't really say which is the "right" way -- normally I would try multiple analyses and see what makes sense in biological context.

**Comment by Manikgarg** [comment]
Thanks a lot!

-Manik

**Comment by JoshuaDanielRubin** [comment]
Hi @cflerin,

Thanks so much for this thread, it is very helpful.

I wonder if I can follow up on this discussion, because I am in a similar situation and have run pySCENIC both separately on disease and healthy, as well as on the combined disease+healthy dataset. Unfortunately I am seeing quite different results in terms of whether there is a difference in activity between disease and healthy cells for my TF of interest.

Therefore, I am struggling to determine which method is more credible/correct. In other words, if running separately I see way more activity for regulons of this TF compared to healthy, but in the combined there is very little difference, how should I best interpret what is happening, or better investigate?

Thanks in advance,
Joshua
