### ISSUE TITLE
[results] Unable to run pyscenic grn

### ISSUE THREAD

**Issue by s849** [aertslab/pySCENIC#214]
Hello,

Thank you for developing PySCENIC. I am having difficulty running the very first step. I have done the following:

1. I processed my data with Seurat and now have transferred to Scanpy and made a loom file to load in PySCENIC with no issues. 
2. When I try to run the !pyscenic grn ... command, I get the following error:
/bin/sh: 1: pyscenic: not found

3. Alternatively, I copied the code for arboreto_with_multiprocessing.py and using nano, saved it as a .py file. When I try to execute it in terminal:

arboreto_with_multiprocessing.py \
    /path/loom.loom \
    /path/hs_hgnc_tfs.txt \
    --method grnboost2 \
    --output adj.tsv \
    --num_workers 20 \
    --seed 777

I get an error that reads: "arboreto_with_multiprocessing.py: command not found". 

I checked and I am using all updated packages (anndata 0.7.4, scanpy 1.6.0, dask 1.0.0).

I have run one data set of ~7K cells in R already but it took over 3 weeks running. I am hoping the Python version can save time. I am new to python so any help will be much appreciated.

Thanks,

**Comment by cflerin** [comment]
Hi @s849 , 

`pyscenic: not found` sounds like your environment isn't active, or you haven't properly installed pyscenic. You only need the `!` if you're running from a jupyter notebook cell, otherwise it's just `pyscenic grn`. To run the script you can use the leading `./` like `./arboreto_with_multiprocessing.py`, or if you haven't set execute permissions on the script, just `python arboreto_with_multiprocessing.py`.

**Comment by s849** [comment]
Thanks! I was able to get it to work. I now have another naive question;

What goes here: {f_db_names} 

Is this a path to the feather files or specific names?
