### ISSUE TITLE
Where can I get databases for track based analysis with cisTarget

### ISSUE THREAD

**Issue by linasieverling** [aertslab/pySCENIC#225]
Hi,

I would like to run the cisTarget step using track based annotation from ENCODE similar to your tutorial on PBMC10k data (https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_SCENIC-protocol-CLI-tracks.ipynb).

Where can I download the respective ranking database and annotation tables for mm10?

Thanks!

**Comment by Coke-Zhang** [comment]
https://resources.aertslab.org/cistarget/

> Hi,
> 
> I would like to run the cisTarget step using track based annotation from ENCODE similar to your tutorial on PBMC10k data (https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_SCENIC-protocol-CLI-tracks.ipynb).
> 
> Where can I download the respective ranking database and annotation tables for mm10?
> 
> Thanks!

https://resources.aertslab.org/cistarget/

**Comment by cflerin** [comment]
Hi @linasieverling ,

Indeed the track-based databases that were used in the PBMC tutorial are available on https://resources.aertslab.org/cistarget/. However there is currently no database available for mm10. They're a bit labor-intensive to generate and there hasn't been a need for it here just yet. But we are working on making a guide so that you could create these yourself. Updates to come.

**Comment by cflerin** [comment]
Similar to #253, and see here: https://github.com/aertslab/create_cisTarget_databases for a possible method to create your own
