### ISSUE TITLE
Command line execution

### ISSUE THREAD

**Issue by HichamAffia** [aertslab/pySCENIC#3]
pyscenic grnboost -o grnboost_output.csv --chunk_size 1 GSE60361_C1-3005-Expression.csv pySCENIC/RESOURCES_FOLDER/Mouse_TFs.txt

2018-03-26 12:39:38,247 - pyscenic.scenic - INFO - Loading expression matrix.
Traceback (most recent call last):
  File "/home/hicham/.local/easybuild/software/2017/Core/miniconda3/4.3.27/bin/pyscenic", line 11, in <module>
    sys.exit(scenic())
  File "/home/hicham/.local/easybuild/software/2017/Core/miniconda3/4.3.27/lib/python3.6/site-packages/pyscenic/scenic.py", line 341, in scenic
    args.func(args)
  File "/home/hicham/.local/easybuild/software/2017/Core/miniconda3/4.3.27/lib/python3.6/site-packages/pyscenic/scenic.py", line 104, in find_adjacencies_command
    if float(n_matching_genes)/n_total_genes < 0.80:
ZeroDivisionError: float division by zero

**Comment by HichamAffia** [comment]
It's as the command line do not read into the Mouse_TFs.txt.
The file is not empty and if I proceed drectly with a python script **float(n_matching_genes)/n_total_genes = 1.0** and n_total_genes is not null
Also the command does not accept a .txt file for the DGE, I just had to write it as csv but I tought you would like to know as the turorial file is a .txt (GSE60361_C1-3005-Expression.txt)

**Comment by bramvds** [comment]
Hi,

Thanks for the remark. If GSE60361_C1-3005-Expression.csv was directly downloaded from GEO and you only changed the extension of the file then the problem is twofold:
1. It is not a comma separated file (CSV) but a tab separated file (TSV) so the filename extension should be changed accordingly.
2. For the file on GEO the columns are the cell IDs and the rows are the gene symbols. Therefore you need to transpose the expression matrix for our tools to work. You can use the -t option for that. [This explains the error message => I'll make sure that a nicer message will be displayed in the next release].

BTW: The option chunk_size has no meaning for grnboost and is only functional for the cox subcommand: I'll release a new version soon that corrects this minor inconsistency.

Hope this helps,
Bram

**Comment by HichamAffia** [comment]
Thank you!
