### ISSUE TITLE
[results]TFs with zero expression level in some cells  have not zero RAS in same cells

### ISSUE THREAD

**Issue by xiaobaicainiao666** [aertslab/pySCENIC#318]
When comparing the gene expression level and RAS of TF, there is a problem:
Some TFs have zero expression level in some cells, but have not zero RAS(regulon activity score)  in same cells.
Is that normal? I think that zero-expression TF's corresponding regulon activity is meaningless in these cells.
Is it because the calculation of RAS(regulon activity score)? Or because I didn't run pyscenic in the right way? 
Thank you very much!

**Comment by xiaobaicainiao666** [comment]
One more question: This is the output of pyscenic ctx.  What do these number mean?  I guess  it is -log10(Pvalue) showing relationship between TF and targets. Bigger number means stronger evidence of TF-target?
![image](https://user-images.githubusercontent.com/61549357/130199672-bf636b6e-107c-4b3d-9716-f7a1420424bb.png)

**Comment by cflerin** [comment]
If a TF has zero expression in all cells, it will not be used for GRN inference, otherwise you will get results using the cells that do have expression values. 

The regulon activity is not directly related to this though. After creating the regulons, each cell is scored based on the activity of the genes in that regulon (the AUCell step). So it is not directly based on TF expression alone, but the entire regulon.

The numbers after the target genes is the importance score from the GRN step.
