### ISSUE TITLE
Which parameter shall we rely on for determining cell type specific regulons, Z score or RSS?

### ISSUE THREAD

**Issue by hyjforesight** [aertslab/pySCENIC#357]
Hello pySCENIC,
We used the scRNA-seq data from mouse intestine and did the SCENIC. We calculated both Z score and RSS for cell clusters and found that the regulons determined by these 2 scores are sometimes different (we run 5 times, and found different in 3 times). Z-score determined regulons are more consistent with the exsiting knowledge.
We are wondering what the exact meaning of RSS is? The paper said we can use RSS to identify regulons that are specific to cell cluster, but how to interpret the RSS is not mentioned.
And which one shall we rely on for determining the cell type specific regulons, Z score or RSS? 

Thanks!
Best,
YJ

**Comment by SeppeDeWinter** [comment]
Hi

It is indeed possible that regulons slightly differ between run, there might be differences in target genes. This is because the importance scoring algorithm is not completely deterministic, so scores will slightly differ. This mainly affects lower ranking genes, which sometimes are and some times are not included in the regulon dependent on the specific score. 

RSS score was first used in this publication: https://doi.org/10.1016/j.celrep.2018.10.045, It is based on Jensen-Shannon divergence. The score will range from 0 to 1; a Regulon will have an RSS score of 1 if it is only active (based on AUCell) in one celltype. In principle the RSS measures how close the Regulon AUC score is to "the perfect situation" where it is only active in one cell type (i.e. most specific). I refer to the paper above for a more technical explanation. 

As to which scoring to use for selecting specific regulons is up to you, there is no scoring mechanism which is perfect and this also depends on the question you're trying to answer.

**Comment by hyjforesight** [comment]
Hello @SeppeDeWinter 
Thanks for the detailed explanation! You're always so nice. We really appreciate it.
