### ISSUE TITLE
[results] Bulk RNA-seq + (pseudobulked?) scRNA-seq?

### ISSUE THREAD

**Issue by mcsimenc** [aertslab/pySCENIC#359]
Hi, I have a question about using bulk RNA-seq and scRNA-seq with SCENIC for a single analysis. Would it be advisable to run SCENIC using a concatenated bulk RNA-seq matrix and a pseudobulked single cell matrix (or full scRNA-seq matrix?), or better to run SCENIC separately on both data sets and combine the results?

**Comment by SeppeDeWinter** [comment]
Hi @mcsimenc, 

This is something we have never tried before. 
You could try both approaches. 

For concatenating bulk RNA-seq and scRNA-seq, I'm afraid this will cause a batch effect due to the two data modalities (e.g. differences in sensitivity of both techniques). This may affect the target genes that are being picked up. I would be careful with this and it would probably need some sort of normalisation to remove this effect.

Running SCENIC separately on both datasets and combining afterwards also is not trivial.

I'm afraid I don't have an easy solution here for you. This is not really what SCENIC was designed for, so it will need some trial and error from your side. I'm not saying that it is impossible to do of course.

Do report back though, I'm curious to see if and how you get it to work.

Good luck.

Seppe

**Comment by mcsimenc** [comment]
I will let you know how this turns out if I do it. Thanks!

**Comment by SeppeDeWinter** [comment]
Good luck! Very curious!
