### ISSUE TITLE
What is the difference between the gene lists of modules.txt and regulon.txt?

### ISSUE THREAD

**Issue by hyjforesight** [aertslab/pySCENIC#369]
Hello pySCENIC,
In the final steps, we can export the gene lists of modules and regulon by the below code for further iRegulon analysis.
I am wondering what the meaning of the 'module' is? Does it correspond to the AUCell UMAP clusters? For example, in this case, we have clusters 0-5 of AUCell UMAP and get gene lists of modules 0-5. In my understanding, 3863 genes of STAT1 module 0 are the target genes controlled by STAT1 in AUCell UMAP cluster 0. Am I right?
Moreover, I'm confused with the gene list of regulon? It has 293 genes, different from the gene list of modules. How is it generated? Which gene list shall I use for iRegulon analysis, module or regulon?
Thanks!
Best,
YJ
 
```python
# pick out modules
tf = 'STAT1'
tf_mods = [ x for x in modules if x.transcription_factor==tf ]

for i,mod in enumerate( tf_mods ):
    print( f'{tf} module {str(i)}: {len(mod.genes)} genes' )
print( f'{tf} regulon: {len(regulons_dict[tf])} genes' )

STAT1 module 0: 3863 genes
STAT1 module 1: 2038 genes
STAT1 module 2: 51 genes
STAT1 module 3: 297 genes
STAT1 module 4: 573 genes
STAT1 module 5: 2763 genes
STAT1 regulon: 293 genes
```
![image](https://user-images.githubusercontent.com/75048821/155873143-1e7ed05e-1d7f-440e-be7a-e143b6072a14.png)
AUCell UMAP cluster 0-5, coresponding to STAT1 module 0-5?

**Comment by SeppeDeWinter** [comment]
Hi YJ.

First of all the modules are not related to the clusters, it's an unlucky coincidence that you have the same number of clusters as modules.

The difference between regulons and modules is the following:

Modules are solely based on co-expression (i.e. before the pruning step based on motif enrichment).
Regulons on the other hand are filtered modules, keeping only genes which have a motif for the TF near their TSS (i.e. after the pruning step).

There are multiple modules because the co-expression values are thresholded using multiple ways  (i.e. selected the genes which are considered as being co-expressed with the TF) . For example, taking the top x genes, taking the 95% quantile, ...

For generating regulons all the genes across the different modules of the same TF are merged.

I hope this clarifies your question, if not feel free to re-open.

Best,

Seppe

**Comment by hyjforesight** [comment]
hello @SeppeDeWinter 
Thanks for the response!
