### ISSUE TITLE
Error when running pyscenic grn

### ISSUE THREAD

**Issue by snoopy-448** [aertslab/pySCENIC#68]
Hi,
When I run this command on our cluster:
`pyscenic grn --num_workers ${ncore} --output ${outdir}/int/1.3_GRNBoost_result.txt ${outdir}/int/1.1_exprMatrix_filtered_t.tsv ${outdir}/int/1.1_inputTFs.txt`
There is an error, seems something related with dask. The message is too long so I attach a file
[sh185423_13214514.err.txt](https://github.com/aertslab/pySCENIC/files/3022397/sh185423_13214514.err.txt)
I set the num_workers to 20 because I use 20 CPUs, I don't know whether it is right. My python3.7 is installed using anaconda. Could you figure out how to solve this problem?
Thanks a lot !

Yang

**Comment by cflerin** [comment]
Hi Yang,

It looks like there are some Dask issues here, including a problem where Dask cannot lock the working directory.  Maybe the comments in [this related issue](https://github.com/dask/distributed/issues/2113) will help you.  In any case, I don't think this is an issue with pySCENIC but rather your install of Dask (and potentially your filesystem as referenced in that issue), so I'll close this, but feel free to reopen if you're still having problems.  Otherwise, 20 CPUs should be fine (depending on your system, make sure you have enough memory as well).  Standard suggestions for this would be to set your Dask version to `1.0.0` and pandas to `0.23.4`.  We also usually use python 3.6.8 instead of 3.7 also.

Chris
