### ISSUE TITLE
RuntimeWarning when running example at modules_from_adjacencies(adjacencies, ex_matrix) step

### ISSUE THREAD

**Issue by milanmlft** [aertslab/pySCENIC#72]
Hi, 

I'm trying to reproduce the example, following the [full pipeline notebook](https://github.com/aertslab/pySCENIC/blob/master/notebooks/pySCENIC%20-%20Full%20pipeline.ipynb) but run into the following **warnings** when running `modules = list(modules_from_adjacencies(adjacencies, ex_matrix))`:

```
.../pyscenic/utils.py:138: RuntimeWarning: invalid value encountered in greater
  regulations = (rhos > rho_threshold).astype(int) - (rhos < -rho_threshold).astype(int)
.../pyscenic/utils.py:138: RuntimeWarning: invalid value encountered in less
  regulations = (rhos > rho_threshold).astype(int) - (rhos < -rho_threshold).astype(int)
```

Any idea what might cause this?

Thanks a lot for your help!

**Comment by bramvds** [comment]
Dear Milan,

You can safely ignore this warning. It is related to the fact that for some TF - target gene interactions discovered by GENIE3/GRNBoost2 there were not sufficient samples to calculate a correlation. The number of samples varies because we mask dropout events in the calculation of these correlations. Hope this helps.

Kindest regards,
Bram
