### ISSUE TITLE
question on positive vs. negative regulons

### ISSUE THREAD

**Issue by dschrein** [aertslab/pySCENIC#75]
I have a situation where the same TF shows up as both a positive and negative regulon in a given cluster of my cells (e.g. Prdm1, Runx2 in the red cluster). Does it just mean that some of its targets are upregulated and some are downregulated? How would I investigate further given the following output files?

adjacencies.p  auc_mtx.csv  df.p  modules.p  motifs.csv  regulons.p

heatmaps are based on cluster-averaged auc matrix values

![image](https://user-images.githubusercontent.com/7146721/57840460-f0492200-77c8-11e9-83ba-208f5230bf88.png)

thanks in advance!

**Comment by bramvds** [comment]
Dear,

Indeed theoretically this means that this TF has two (disjoint) sets of targetomes: a set of target genes which the factor controls as a transcriptional activator (+ regulon) and a disjoint set of target genes for which the factor acts as a transcriptional repressor (- regulon). However, this relationship between a factor and a target genes is inferred from correlation patterns only. We briefly assessed the relevance of "negative regulons" via the well-known transcriptional repressor REST in a relevant dataset (Zeisel et al.) and decided to focus only on the "positive" regulons. Because of this, by default, pySCENIC only returns "positive" regulons.

Hope this helps,
Bram
