### ISSUE TITLE
 Subsetting AUCmatrix; Understanding the output after pruning; 

### ISSUE THREAD

**Issue by saeedfc** [aertslab/pySCENIC#94]
Hi,

I have a few doubts regarding the output. I really appreciate your help on these.
Thanks in advance!

1) If I derive AUCELL matrix for an expression matrix of n cells, Can I still use the same AUCELL matrix to work with a subset of the data (say m cells, m<n) ? Or do I have to rerun SCENIC for the subset of m cells of the data separately? (Asking because I don't know whether there is any pan data nomalization or dependency generated internally in the workflow)

2)After pruning we obtain a data frame with the transcription factor and their targets. In paranthesis of each target gene, a value is given. What is this value?

Thanks again!

**Comment by cflerin** [comment]
Hi,

In general, yes, it's fine to use a subset of the AUCell matrix for a specific set of cells that you're interested in (no reason to re-run SCENIC just for this). However, it's important to note that the AUCell values for each cell do depend on the other cells during the calculation. The reason is that the cells are first ranked (by expression), so using only a subset of cells will alter the ranking and therefore the AUCell scores. So if you look at the cell enrichment scores in a specific cluster of cells, it will show cell activity within the context of the full set of cells.

For your second question, these scores represent the weight of the target genes that define the signature (this is the output of the cisTarget step, calculating motif enrichment and defining regulons).

Sorry for the late reply, but hopefully this answers your questions.

**Comment by saeedfc** [comment]
Hi,

Thanks a lot. Yes they answer my question and I was waiting exactly for this :-).
